// Generated by https://quicktype.io
class Peliculas{

  List<Pelicula> items = new List();

  Peliculas();

  Peliculas.fromJsonList( List<dynamic> jsonList ){
    if (jsonList == null) return;

    for (var item in jsonList ){
      final pelicula =  new Pelicula.fromJsonMap(item);
      items.add(pelicula);
    }
  }

}

class Pelicula {

  String uniqueId;

  double voteAverage;
  int id;
  int voteCount;
  String releaseDate;
  double popularity;
  bool adult;
  String backdropPath;
  List<int> genreIds;
  String overview;
  String originalLanguage;
  String originalTitle;
  String posterPath;
  String title;
  bool video;

  Pelicula({
    this.voteAverage,
    this.id,
    this.voteCount,
    this.releaseDate,
    this.popularity,
    this.adult,
    this.backdropPath,
    this.genreIds,
    this.overview,
    this.originalLanguage,
    this.originalTitle,
    this.posterPath,
    this.title,
    this.video,
  });

  Pelicula.fromJsonMap( Map <String, dynamic> json){
    voteAverage     = json ['vote_average'] /1 ;
    id              = json ['id'];
    voteCount       = json ['vote_count'];
    releaseDate     = json ['release_date'];
    popularity      = json ['popularity'] /1;
    adult           = json ['adult'];
    backdropPath    = json ['backdrop_path'];
    genreIds        = json ['genre_ids'].cast<int>();
    overview        = json ['overview'];
    originalLanguage = json ['original_language'];
    originalTitle   = json ['original_title'];
    posterPath      = json ['poster_path'];
    title           = json ['title'];
    video           = json ['video'];
  }

  getPosterImg(){
    
    if (posterPath == null){
      return 'https://clients.cylindo.com/viewer/3.x/v3.0/documentation/img/not_found.gif';
    }

    return 'https://image.tmdb.org/t/p/w500/$posterPath';
  }

  getBackgroundImg(){
    
    if (backdropPath == null){
      return 'https://clients.cylindo.com/viewer/3.x/v3.0/documentation/img/not_found.gif';
    }

    return 'https://image.tmdb.org/t/p/w500/$backdropPath';
  }
}
